spring.application.name=inventario
server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:inventario}
spring.datasource.username=${POSTGRES_USER:inventario}
spring.datasource.password=${POSTGRES_PASSWORD:inventario}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health
